name: Test Action

on:
  push:

jobs:
  secrets:
    name: Secret Action
    runs-on: ubuntu-20.04

    steps:
      - name: First steps
        run: |
          echo "1..."
          echo "2..."
          echo "3..."
      - name: Print secret
        run:  echo "${{ secrets.MY_SECRET }}"
      - name: Cleanup
        run:  echo Goodbye

