name: Test Action

on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: Test Action
    if: contains(github.event.issue.labels.*.name, 'autotip')

    runs-on: ubuntu-20.04

    steps:
      - name: Install Dependencies
        run: |
           sudo apt-get update && sudo apt-get install -y --no-install-recommends jq

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run GitHub issue forms parser
        id: issue-parser
        uses: edumserrano/github-issue-forms-parser@v1
        with:
          template-filepath: '.github/ISSUE_TEMPLATE/new-tip.yml'
          issue-form-body: '${{ github.event.issue.body }}'
      - name: Output parsed issue (bash)
        run: |
          echo ${{ steps.issue-parser.outputs.parsed-issue.title }}
      - name: Output parsed issue (python/1)
        run: |
          ./parsejson.py '${{ steps.issue-parser.outputs.parsed-issue }}' || true
      - name: Output parsed issue (python/2)
        run: |
          ./parsejson.py ${{ steps.issue-parser.outputs.parsed-issue }} || true
      - name: Output parsed issue (JQ/bash)
        run: |
          filename=$(echo "${{ steps.issue-parser.outputs.parsed-issue }}" | jq -r ".filename")
          echo "FILE: $filename"
          title=$(echo "${{ steps.issue-parser.outputs.parsed-issue }}" | jq -r ".title")
          echo "TITLE: $title"
          description=$(echo "${{ steps.issue-parser.outputs.parsed-issue }}" | jq -r ".description" | sed -e '1d' -e '$d')
          echo "DESCRIPTION: $description"
          image=$(echo "${{ steps.issue-parser.outputs.parsed-issue }}" | jq -r ".image" | sed -e 's|.*](||' -e 's|).*||')
          echo "IMAGE: $image"
