---
name: Test Action

on:
  push:

jobs:
  test:
    name: Test Action
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        float: [32, 64]
        msystem:
          - mingw32
          - mingw64
        experimental:
          - false
        include:
          - msystem: clangarm64
            experimental: true
    steps:
      - name: test
        run: |
          echo test
