name: Test Action

on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: Test Action
    if: contains(github.event.issue.labels.*.name, 'autotip')

    runs-on: ubuntu-20.04

    steps:
      - name: Install Dependencies
        run: |
           sudo apt-get update && sudo apt-get install -y --no-install-recommends jq

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run GitHub issue forms parser
        id: issue-parser
        uses: edumserrano/github-issue-forms-parser@v1
        with:
          template-filepath: '.github/ISSUE_TEMPLATE/new-tip.yml'
          issue-form-body: '${{ github.event.issue.body }}'
      - name: Output parsed issue
        run: |
          ./parsejson.py '${{ steps.issue-parser.outputs.parsed-issue }}' || true
	  ls -lha
          find . -maxdepth 1 -type f -exec md5sum {} +
