name: Test Action

on:
  issues:
    types: [opened, reopened]

jobs:
  test:
    name: Test Action
    if: contains(github.event.issue.labels.*.name, 'autotip')

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run GitHub issue forms parser
        id: issue-parser
        uses: edumserrano/github-issue-forms-parser@v1
        with:
          template-filepath: '.github/ISSUE_TEMPLATE/new-tip.yml'
          issue-form-body: '${{ github.event.issue.body }}'
      # The next step is using powershell to parse the action's output but you can use whatever you prefer.
      # Note that in order to read the step outputs the action step must have an id.
      - name: Output parsed issue
        run: |
          echo ${{ steps.issue-parser.outputs.parsed-issue }}
